import type { CardDefinition } from '../game/types';

// 'paladin' is not imported from cards.ts (circular import): same pattern as mageCards.ts.
export const PALADIN = 'paladin';

// PURELY PLACEHOLDER cards (user, 2026-10-09: "purely placeholder cards, no paladin inspired card
// names"). They exist to prove the second-hero plumbing and to exercise Radiant Light, the Paladin's
// placeholder resource: it starts at 0 each fight, carries between turns, and is generated by cards
// (never automatically). Some cards cost Radiant Light instead of energy (`costResource`). Every
// name and number is a provisional stand-in; real Paladin design is the user's.
// Text is generated from `effects` (game/describe.ts).

const base = { owner: PALADIN, inRewardPool: true, inStarterPool: true } as const;

/** The user's own example: "gain X block, gain X Radiant Light". */
export const PLACEHOLDER_BLOCK_LIGHT: CardDefinition = {
  ...base,
  id: 'placeholder-block-light',
  name: 'Block + Light',
  type: 'skill',
  cost: 1,
  effects: [
    { kind: 'block', value: 6 },
    { kind: 'gainRadiantLight', value: 2 },
  ],
  upgrade: { effects: [{ kind: 'block', value: 8 }, { kind: 'gainRadiantLight', value: 3 }] },
};

export const PLACEHOLDER_ATTACK_LIGHT: CardDefinition = {
  ...base,
  id: 'placeholder-attack-light',
  name: 'Attack + Light',
  type: 'attack',
  target: 'enemy',
  cost: 1,
  effects: [
    { kind: 'damage', value: 5 },
    { kind: 'gainRadiantLight', value: 1 },
  ],
  upgrade: { effects: [{ kind: 'damage', value: 7 }, { kind: 'gainRadiantLight', value: 2 }] },
};

export const PLACEHOLDER_LIGHT_GAIN: CardDefinition = {
  ...base,
  id: 'placeholder-light-gain',
  name: 'Light Gain',
  type: 'skill',
  cost: 1,
  effects: [{ kind: 'gainRadiantLight', value: 3 }],
  upgrade: { effects: [{ kind: 'gainRadiantLight', value: 5 }] },
};

export const PLACEHOLDER_PLAIN_ATTACK: CardDefinition = {
  ...base,
  id: 'placeholder-plain-attack',
  name: 'Plain Attack',
  type: 'attack',
  target: 'enemy',
  cost: 2,
  effects: [{ kind: 'damage', value: 12 }],
  upgrade: { effects: [{ kind: 'damage', value: 16 }] },
};

// ---- cards paid for in Radiant Light ----

export const PLACEHOLDER_LIGHT_ATTACK: CardDefinition = {
  ...base,
  id: 'placeholder-light-attack',
  name: 'Light Attack',
  type: 'attack',
  target: 'enemy',
  cost: 2,
  costResource: 'radiantLight',
  effects: [{ kind: 'damage', value: 14 }],
  upgrade: { effects: [{ kind: 'damage', value: 18 }] },
};

export const PLACEHOLDER_LIGHT_BLOCK: CardDefinition = {
  ...base,
  id: 'placeholder-light-block',
  name: 'Light Block',
  type: 'skill',
  cost: 2,
  costResource: 'radiantLight',
  effects: [{ kind: 'block', value: 14 }],
  upgrade: { effects: [{ kind: 'block', value: 18 }] },
};

export const PLACEHOLDER_LIGHT_DRAW: CardDefinition = {
  ...base,
  id: 'placeholder-light-draw',
  name: 'Light Draw',
  type: 'skill',
  cost: 1,
  costResource: 'radiantLight',
  effects: [{ kind: 'draw', value: 2 }],
  upgrade: { effects: [{ kind: 'draw', value: 3 }] },
};

export const PLACEHOLDER_LIGHT_DEBUFF: CardDefinition = {
  ...base,
  id: 'placeholder-light-debuff',
  name: 'Light Debuff',
  type: 'attack',
  target: 'enemy',
  cost: 1,
  costResource: 'radiantLight',
  effects: [
    { kind: 'damage', value: 4 },
    { kind: 'applyStatus', status: 'weak', value: 1, to: 'target' },
  ],
  upgrade: { effects: [{ kind: 'damage', value: 6 }, { kind: 'applyStatus', status: 'weak', value: 2, to: 'target' }] },
};

export const PLACEHOLDER_LIGHT_BURST: CardDefinition = {
  ...base,
  id: 'placeholder-light-burst',
  name: 'Light Burst',
  type: 'attack',
  target: 'enemy',
  cost: 5,
  costResource: 'radiantLight',
  exhaust: true,
  effects: [{ kind: 'damage', value: 36 }],
  upgrade: { effects: [{ kind: 'damage', value: 48 }] },
};

export const PLACEHOLDER_LIGHT_ENGINE: CardDefinition = {
  ...base,
  id: 'placeholder-light-engine',
  name: 'Light Engine',
  type: 'power',
  cost: 2,
  onTurnStartEffect: { kind: 'gainRadiantLight', value: 1 },
  upgrade: { onTurnStartEffect: { kind: 'gainRadiantLight', value: 2 } },
};

/** Every placeholder Paladin card. */
export const PALADIN_CARDS: CardDefinition[] = [
  PLACEHOLDER_BLOCK_LIGHT,
  PLACEHOLDER_ATTACK_LIGHT,
  PLACEHOLDER_LIGHT_GAIN,
  PLACEHOLDER_PLAIN_ATTACK,
  PLACEHOLDER_LIGHT_ATTACK,
  PLACEHOLDER_LIGHT_BLOCK,
  PLACEHOLDER_LIGHT_DRAW,
  PLACEHOLDER_LIGHT_DEBUFF,
  PLACEHOLDER_LIGHT_BURST,
  PLACEHOLDER_LIGHT_ENGINE,
];
